FROM ubuntu:focal

ENV USER=app
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"


WORKDIR /app

COPY target/release/backend ./

USER app:app

EXPOSE 3000

CMD ["/app/backend"]
