apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: jammeri/pingpong:1.5
          env:
            - name: SERVER
              valueFrom:
                secretKeyRef:
                  name: dburl
                  key: server

