apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/service-backend.yaml
- manifests/ingress.yaml
- manifests/secret.enc.yaml
- manifests/persistentvolumeclaim.yaml
images:
- name: IMAGEBACKEND
  newName: jammeri/backend
- name: IMAGEFRONTEND
  newName: jammeri/project
