apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: backend
          image: jammeri/backend:1.8
          env:
           - name: SERVER
             valueFrom:
               secretKeyRef:
                 name: dburl
                 key: server
        - name: web
          image: jammeri/project:1.21
          volumeMounts:
            - name: data
              mountPath: /data

