apiVersion: v1
kind: Service
metadata:
  name: project-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: project
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3001
