apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  namespace: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: logger-claim
      containers:
        - name: logger-writer
          image: jammeri/logger:writer-1.0
          volumeMounts:
            - name: data
              mountPath: /data
        - name: logger-web
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logger-configmap
                  key: message
          image: jammeri/logger:web-1.2
          volumeMounts:
            - name: data
              mountPath: /data
