apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logger-claim
  namespace: pingpong
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
